### PR TITLE
Fix jupyter

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by surrutiaquir** [comment]
Hi @chrisburr,
I'm sorry for bothering you but I noticed you were able to successfully solve the issue shown here [https://sft.its.cern.ch/jira/browse/ROOT-10884](url) by installing the patch. I'm having the same problem but I don't know how to install the patch so I was wondering if you could address me about it. I apologize for such a naive question.

**Comment by henryiii** [comment]
Can you just install the patch here: https://patch-diff.githubusercontent.com/raw/root-project/root/pull/6165.patch ?

Info about applying a patch can be found here: https://www.drupal.org/patch/apply

**Comment by surrutiaquir** [comment]
I guess I have another question, even more basic: should I install the patch in my machine, where ROOT is installed, or do I need to re-install ROOT to include the patch? I'm so sorry...

**Comment by henryiii** [comment]
You will need to reinstall.

I think you can just update to 6-22-02, however, which includes the patch?

**Comment by henryiii** [comment]
If you happen to be using brew, I've pushed a bump to that formula too: https://github.com/Homebrew/homebrew-core/pull/60123

**Comment by surrutiaquir** [comment]
Thank you so much, I did it!

**Pull request merged**
