### PR TITLE
Preserve external ROOTSYS in activate/deactivate cycle

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR modifies the `{de}activate.sh` scripts to preserve an existing `ROOTSYS` variable setting so that it can be reinstated upon environment deactivation.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by henryiii** [comment]
fish and csh activate/deactivate should also be included in any changes.

**Comment by duncanmmacleod** [comment]
> fish and csh activate/deactivate should also be included in any changes.

Ah yes, forgot those, will post another commit shortly (after some googling).

**Comment by duncanmmacleod** [comment]
Ok, I have updated the other shell scripts, but am not a user of csh or fish, so have little idea if the script changes actually work.

**Comment by chrisburr** [comment]
Included in #155

**Pull request closed without merging**
