### PR TITLE
cfitsio400 (take 3)

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR is a fork of #151 with minor edits to the recipe to get the linux/osx-64 builds to pass.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@chrisburr, can the osx-arm64 builds be formally disabled as well? I think you are manually providing those builds, so having the config in the repo is useful, but a green CI grid is very cathartic.

**Comment by duncanmmacleod** [comment]
@conda-forge/root, what can be done to get this merged? Since a number of LIGO packages have already migrated to cfitsio400, we're stuck waiting for this for a few things.

**Comment by duncanmmacleod** [comment]
Ping @conda-forge/root (sorry to nag).

**Comment by henryiii** [comment]
I've generally been leaving merges up to @chrisburr, since he builds the ARM packages locally. I also have a AS machine I can build locally on, so if I can figure out how to set it up & upload releases, I could merge.

**Comment by duncanmmacleod** [comment]
@chrisburr, I have included the changes from #144 here as well, any objections to me also folding in the patch from #152 (which is a backport of https://github.com/root-project/root/commit/29c5501983ff3945478014000de06a1fd6ef619a?

**Comment by chrisburr** [comment]
@duncanmmacleod Go ahead. I'm also going to fold other maintenance I wanted to do into this PR but I'll make sure to merge it by the end of tomorrow (I'm waiting for llvm and clang to be rebuilt which takes about a day to work itself through the CI).

Also sorry for having been unresponsive lately, I'll hopefully be more on top of things soon.

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod Go ahead. I'm also going to fold other maintenance I wanted to do into this PR but I'll make sure to merge it by the end of tomorrow (I'm waiting for llvm and clang to be rebuilt which takes about a day to work itself through the CI).

Thanks.

> 
> Also sorry for having been unresponsive lately, I'll hopefully be more on top of things soon.

No need to apologise, everyone has other things to do, and they are all better than listening to me.

**Comment by duncanmmacleod** [comment]
Ok, @chrisburr, I've added two commits from #152, and I think I'm done with this one. If you need any help from me to get this over the line, please don't hesitate to ask. Thanks again for picking this up.

**Comment by chrisburr** [comment]
Manually build and uploaded for `osx-arm64`. Logs are:

* [osx_arm64_numpy1.19python3.8.____cpython.log](https://github.com/conda-forge/root-feedstock/files/7874431/osx_arm64_numpy1.19python3.8.____cpython.log)
* [osx_arm64_numpy1.19python3.9.____cpython.log](https://github.com/conda-forge/root-feedstock/files/7874429/osx_arm64_numpy1.19python3.9.____cpython.log)

**Pull request merged**
