### PR TITLE
Add a patch to remove erroneous delete

### PR DESCRIPTION
**Pull request by evonreis**
Add a patch to remove erroneous delete that causes 'double free' crashes when calling TGText::AsString().

Bug causes TGTextEdit::Copy() to crash.  It makes that widget essentially unusable.

Fix is backported from ROOT master branch.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x ] Bumped the build number (if the version is unchanged)
* [x ] Ensured the license file is being packaged.

Change should not have any effects outside the bug fix.

### CODE REVIEW

**Comment by evonreis** [comment]
@conda-forge-admin please rerender

**Comment by henryiii** [comment]
The patch needs to be listed in the recipe too.

**Comment by evonreis** [comment]
Sorry about that.  Patch added to meta.yaml.

**Comment by evonreis** [comment]
@conda-forge-admin please rerender

**Comment by evonreis** [comment]
@henryiii Could you help me with this pull request?  It's a very small patch that fixes a bug introduced in ROOT 6.22.  This bug breaks key software at LIGO.  

This patch was already accepted into ROOT master branch but they haven't moved it to 6.24. They probably won't.  

As far as I can tell, the patch is now applied correctly in a conda build, but the automatic CI builds (see above), all time out after almost an hour. 

What more can I do to get this accepted?

**Comment by henryiii** [comment]
I can try to help after a grant deadline tomorrow; @chrisburr might be available sooner. I think we are still building AS wheels locally, @chrisburr? I haven't set up my Mac mini to do that yet. @chrisburr is there a setting for the run length? I think builds usually take more than an hour. Also, there's currently an issue where the latest SDK breaks this even though it's not supposed to be dependent on it.

**Comment by henryiii** [comment]
It's not a timeout problem, it's:

```
/home/conda/feedstock_root/build_artifacts/root_base_1636481111836/work/build-dir/etc/cling/std.modulemap:368:10: error: module 'std.codecvt' is incompatible with feature 'header_existence'
  module "codecvt" {
         ^
/home/conda/feedstock_root/build_artifacts/root_base_1636481111836/_build_env/bin/../lib/gcc/../../x86_64-conda-linux-gnu/include/c++/9.4.0/bits/fs_path.h:40:10: note: submodule of top-level module 'std' implicitly imported here
#include <codecvt>
         ^

```

**Comment by chrisburr** [comment]
Included in #155

**Pull request closed without merging**
