### PR TITLE
Patch to add tbox hex type from the branch cherry-pick into CMS root repo.

### PR DESCRIPTION
**Pull request by gartung**
https://github.com/root-project/root/commit/a3988dbed4bb20aebc4dce2249899d80230870c8

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by henryiii** [comment]
Was this PR’d to upstream ROOT?

**Comment by gartung** [comment]
It's not clear to me if it ever was.

**Comment by gartung** [comment]
Yes it was merged to master at least

https://github.com/root-project/root/pull/2985

**Comment by gartung** [comment]
https://github.com/root-project/root/commit/a3988dbed4bb20aebc4dce2249899d80230870c8

**Comment by henryiii** [comment]
Okay, let's call it `patches/root-6.18.00-add-tbox-hex.patch` and maybe add a little note as to why it's needed. (pretty sure it was not backported to 6.16.02).

**Pull request merged**
