### PR TITLE
Update to 6.22

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by henryiii** [comment]
The linking patch was just merged into ROOT (master and 6-22 patches)!

**Comment by henryiii** [comment]
Unrelated: This is the first time I've noticed that conda-forge dropped support by default for Python 2.7 in January.

**Comment by chrisburr** [comment]
> The linking patch was just merged into ROOT (master and 6-22 patches)!

Thanks for tracking this, you saved me a fair bit of time by mentioning it before I hit that issue! :)

> Unrelated: This is the first time I've noticed that conda-forge dropped support by default for Python 2.7 in March.

Yeah, there is a label that can be used to make sure you get frozen view how the channel was before Python 2 was dropped (`conda-forge/label/cf202003`). I haven't tried using the workaround to keep Python 2 support in feedstocks (for now, I might have to for LHCbDIRAC as that is still going to take a year or so to migrate...).

**Comment by henryiii** [comment]
For packages that are actively supporting Python 2, it might be a good idea to re-add the support; many of Conda-forge's packages (like NumPy, Numba, etc) have already dropped Python 2 upstream so it doesn't matter all that much that they also are not rebuilding. However, if a rebuild is needed in the future for a migration or something, they won't rebuild Python 2 for those packages for it, so eventually I assume it might break. ROOT would be hit by that pretty easily, since it depends on so much.

**Comment by eguiraud** [comment]
```
2020-06-15T12:44:03.3746230Z [ 37%] Copying /Users/runner/miniforge3/conda-bld/root_1592224075304/work/root-source/icons/geotrd2_s.xpm
2020-06-15T12:44:03.3907830Z /Users/runner/miniforge3/conda-bld/root_1592224075304/work/root-source/interpreter/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp:28:10: fatal error: 'llvm/Config/config.h' file not found
2020-06-15T12:44:03.3908910Z #include "llvm/Config/config.h" // Get configuration settings
2020-06-15T12:44:03.3909380Z          ^~~~~~~~~~~~~~~~~~~~~~
2020-06-15T12:44:03.4166190Z [ 37%] Copying /Users/runner/miniforge3/conda-bld/root_1592224075304/work/root-source/icons/geotrd2_t.xpm
2020-06-15T12:44:03.4391590Z 1 error generated.
2020-06-15T12:44:03.4464290Z make[2]: *** [interpreter/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/build.make:280: interpreter/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/DynamicLibraryManagerSymbol.cpp.o] Error 1
2020-06-15T12:44:03.4468440Z make[2]: Leaving directory '/Users/runner/miniforge3/conda-bld/root_1592224075304/work/build-dir'
2020-06-15T12:44:03.4469610Z make[1]: *** [CMakeFiles/Makefile2:6484: interpreter/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/all] Error 2
2020-06-15T12:44:03.4470500Z make[1]: *** Waiting for unfinished jobs....
```
:thinking:

**Comment by chrisburr** [comment]
When moving the build from my fork I forgot I needed to export patches for https://sft.its.cern.ch/jira/browse/ROOT-10812

**Pull request merged**
