### PR TITLE
Update to 6.20

### PR DESCRIPTION
**Pull request by chrisburr**
TODO:

- [x] ~Remove `-Wl,--exclude-libs` hack is it might have been fixed by https://github.com/root-project/root/commit/08e767cb06717d3c90ddf6834a82cec0cb91937a~ The hack is still needed.
- [x] Disable `builtin_ftgl` (https://github.com/conda-forge/staged-recipes/pull/10561)
- [x] Remove `SetLibraryPath()` in `rootx/src/rootx.cxx` in ROOT when `-Drpath=ON` (currently patched with `sed`(https://github.com/root-project/root/pull/4757)
- [ ] Check that all Python packages in `lib/` are being symlinked correctly

### CODE REVIEW

**Comment by henryiii** [comment]
Python 2.7 + macOS couldn't find OpenGL... But the other Python versions on macOS could?

**Comment by chrisburr** [comment]
Yup and it still works for 6.18.04, I haven’t tried reproducing it locally yet.

**Comment by chrisburr** [comment]
> Python 2.7 + macOS couldn't find OpenGL... But the other Python versions on macOS could?

Fixed in https://github.com/root-project/root/pull/4832

**Comment by chrisburr** [comment]
🎉 🎉 🎉 🎉 🎉!!!

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
