### PR TITLE
WIP: Backport to 6.14.06

### PR DESCRIPTION
**Pull request by henryiii**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by henryiii** [comment]
Note: This should not be merged, but should become a new branch (once complete).

**Comment by chrisburr** [comment]
Looks like the macOS static linking patch needs backporting as it doesn't apply cleanly.

**Comment by henryiii** [comment]
Don’t make a new branch yet if it passes. Need to look into the kernel patch and the splitup PR first.

**Comment by chrisburr** [comment]
The failure is harmless and just due to a network glitch after the build succeeded.

**Comment by henryiii** [comment]
Should we go ahead and put this in a branch? I was waiting until the split happened, but seems like that's rather long term.

**Comment by chrisburr** [comment]
Is there a motivation for adding 6.14 and not 6.16?

**Comment by henryiii** [comment]
@ adamdddave needed this at one point, something was broken in 6.16. He said it's fine now, so let's close this and only reopen it if someone needs the old version. I'd prefer not to maintain old versions if possible.

Also, the release of 6.16 was pretty good on Conda-Forge, but 6.14 still had some bugs that were solved later.

**Pull request closed without merging**
