### PR TITLE
Fix osx target for arm64

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Needed for https://github.com/conda-forge/yoda-feedstock/pull/17

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready for review @conda-forge/root

**Comment by Tobias-Fischer** [comment]
Ah actually I'm not sure what's going on with the arm-64 builds - they seem to be failing on the main branch, too. Any hints @conda-forge/root?

**Comment by henryiii** [comment]
Root doesn’t support cross compilation so @chrisburr always compiles this manually on a native M1.

**Comment by Tobias-Fischer** [comment]
I see. @chrisburr please let me know if you want me to build the package with this change.

**Comment by chrisburr** [comment]
Thanks for looking into this @Tobias-Fischer :+1:

I'll merge now and build the packages this evening.

**Comment by Tobias-Fischer** [comment]
Hi @chrisburr, kind reminder re the osx-arm64 build :)

**Pull request merged**
