### PR TITLE
Starting split

### PR DESCRIPTION
**Pull request by henryiii**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by henryiii** [comment]
Instead of trying to do this by removing everything then putting things back in as needed, I think I'll try this from the other direction; dropping one package at a time. I'll need to set up a local env that doesn't hit the "bits" error as well. More later today.

**Comment by henryiii** [comment]
The PCH is still "missing" on Linux, it looks like.

**Comment by chrisburr** [comment]
Hmm, it behaves different when I run it locally. Let's see:

@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
I'm squashing and rebasing, OK to push?

**Comment by chrisburr** [comment]
Go ahead

**Comment by henryiii** [comment]
Looks like an issue with fftw and mpi?

**Comment by chrisburr** [comment]
Yeah...

I'm trying to see if it's caused by the new package format (https://www.anaconda.com/how-we-made-conda-faster-4-7/).

**Comment by minrk** [comment]
I think there's something wrong in the solver if it's picking up multiple incompatible builds of fftw and not resolving the incompatibility. Adding explicit `fftw * nompi*` to the dependencies should let you work around this for now by making the restriction to fftw without mpi explicit rather than relying on the solver to pick the right one.

**Pull request closed without merging**
