### PR TITLE
Fix opengl

### LINKED ISSUE #25: Please add build of libEve and associated GL libraries
Hi,

I am building the CMS Fireworks application in conda and I am using your excellent root package. The root package seems to be missing libEve and associated GL libraries. When I run my build I get errors from these include statements shown below. If this is just a matter of setting the correct CMake flags for the ROOT build I will submit a PR with those changes.

 #include "TEveArrow.h"
 #include "TEveBox.h"
 #include "TEveBoxSet.h"
 #include "TEveCaloData.h"
 #include "TEveCaloData.h"
 #include "TEveCalo.h"
 #include "TEveCompound.h"
 #include "TEveDigitSet.h"
 #include "TEveElement.h"
 #include "TEveGeoNode.h"
 #include "TEveGeoShape.h"
 #include "TEveJetCone.h"
 #include "TEveLegoEventHandler.h"
 #include "TEveManager.h"
 #include "TEvePointSet.h"
 #include "TEveProjectionBases.h"
 #include "TEveScalableStraightLineSet.h"
 #include "TEveScene.h"
 #include "TEveShape.h"
 #include "TEveStraightLineSet.h"
 #include "TEveTrack.h"
 #include "TEveTrackPropagator.h"
 #include "TEveTrans.h"
 #include "TEveTreeTools.h"
 #include "TEveUtil.h"
 #include "TEveVector.h"
 #include "TEveViewer.h"
 #include "TEveVSDStructs.h"
 #include "TEveWindow.h"
 #include "TGLFontManager.h"
 #include "TGLIncludes.h"
 #include "TGLObject.h"
 #include "TGLOrthoCamera.h"
 #include "TGLPerspectiveCamera.h"
 #include "TGLScenePad.h"
 #include "TGLUtil.h"
 #include "TGLViewer.h"
 #include "TGLViewer.h" // access to over-all bounding box
 #include "TGLWidget.h"

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Changes:
 * Fixes #25 by adding `-Dopengl=ON`
 * Uses Anaconda Inc's [CMake recommendations](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html?highlight=cmake#an-aside-on-cmake-and-sysroots)
 * Add support for `ROOT_JENKINS_GIT_URL`, `ROOT_JENKINS_GIT_URL` and `ROOT_RUN_GTESTS` environment variables so ROOT's nightlies can use this recipe directly
 * Use GNU `sed` from conda-forge for patching the sources instead of relying on the host
 * Copy the [upstream `FindX11.cmake`](https://github.com/Kitware/CMake/blob/e59e17c1c7059b7d0f02d6b12bc3094a2afee778/Modules/FindX11.cmake) file and add minor patches as I couldn't figure out how to configure CMake correctly

### CODE REVIEW

**Comment by chrisburr** [comment]
I've build this and uploaded the binary to my own channel. Trying it on lxplus gives some kind of error from OpenGL's dynamic linking to LLVM:

```bash
$ conda create --name test-root-opengl -c chrisburr/label/opengl root python=3.7
$ conda activate test-root-opengl
# It doesn't happen when `root -b` is used
$ root -l -q -x -e 'gStyle->SetCanvasPreferGL(kTRUE); c = new TCanvas(); if (!c->UseGL()) { throw std::runtime_error("OpenGL does not appear to be working");}'

: CommandLine Error: Option 'help-list' registered more than once!
terminate called after throwing an instance of 'std::runtime_error'
  what():  >>> Interpreter compilation error:
inconsistency in registered CommandLine options
```

I've ran out of time to do any more debugging today but this looks relevant: https://github.com/root-project/cling/issues/201#issuecomment-409573736

**Comment by chrisburr** [comment]
I've marked this as ready to review as I'm not sure how much of a problem this is. So far as I can tell it only affects using X11 forwarding from CentOS 7 and it can be worked around by setting `export LIBGL_ALWAYS_INDIRECT=1` before launching `root`.

**Comment by gartung** [comment]
> I've marked this as ready to review as I'm not sure how much of a problem this is. So far as I can tell it only affects using X11 forwarding from CentOS 7 and it can be worked around by setting `export LIBGL_ALWAYS_INDIRECT=1` before launching `root`.

@chrisburr The docker image used for the ci builds is centos 6.10. Maybe this is partly to blame for the X11 error.

**Comment by gartung** [comment]
I am getting same error running directly on my SL7 desktop.

**Comment by gartung** [comment]
```
LIBGL_ALWAYS_INDIRECT=1  root -x "${ROOTSYS}/tutorials/eve/geom_lhcb.C" 
   ------------------------------------------------------------
  | Welcome to ROOT 6.16/00                  https://root.cern |
  |                               (c) 1995-2018, The ROOT Team |
  | Built for linuxx8664gcc on Apr 13 2019, 23:33:00           |
  | From tag , 23 January 2019                                 |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

root [0] 
Processing /data/anaconda2/envs/test-root-opengl/tutorials/eve/geom_lhcb.C...
TEveManager::GetGeometry  loading: 'http://root.cern.ch/files/lhcbfull.root' -> 'http://root.cern.ch/files/lhcbfull.root'.
Info in <TGeoManager::Import>: Reading geometry from file: http://root.cern.ch/files/lhcbfull.root
[TFile::Cp] Total 0.32 MB	|====================| 100.00 % [0.6 MB/s]
Info in <TFile::OpenFromCache>: using local cache copy of http://root.cern.ch/files/lhcbfull.root [./files/lhcbfull.root]
Info in <TGeoManager::CloseGeometry>: Geometry loaded from file...
Info in <TGeoManager::SetTopVolume>: Top volume is World. Master volume is World
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Info in <TGeoManager::CloseGeometry>: Voxelization retrieved from file
Info in <TGeoManager::CountLevels>: max level = 8, max placements = 277
Info in <TGeoManager::CloseGeometry>: 18491756 nodes/ 709 volume UID's in default geometry
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
Info in <TGeoManager::SetVisLevel>: Automatic visible depth disabled
Error in <TGLViewerBase::RenderOpaque - pre exit check>: GL Error invalid operation
Error in <RootX11ErrorHandler>: 255 (TGLWidget XID: 56623712, XREQ: 152)
TGLWidget:	56623712
	TGVerticalFrame:	56623707
	TGLSAFrame:	56623696
	TGCompositeFrame:	56623695
	TEveCompositeFrameInTab:	56623688
	TGCompositeFrame:	56623687
	TGTab:	56623237
	TGHorizontalFrame:	56623228
	TGVerticalFrame:	56623227
	TGHorizontalFrame:	56623225
	TGVerticalFrame:	56623214
	TEveBrowser:	56623213
```

**Comment by gartung** [comment]
How can I install the conda package created by the docker build?

**Comment by gartung** [comment]
To answer my own question 
conda create -c file://$PWD/build_artifacts root -n myrootenv
seems to work.

**Comment by gartung** [comment]
I used this PR and built with docker on my SL7 desktop using the linux-python2.7 config. Creating an environment using the build_artifacts directory as a channel and running from that environment I can run without error
```
env LIBGL_ALWAYS_INDIRECT=1 root -e 'gStyle->SetCanvasPreferGL(kTRUE); c = new TCanvas(); if (!c->UseGL()) { throw std::runtime_error("OpenGL does not appear to be working"); }'

env LIBGL_ALWAYS_INDIRECT=1 root -l -x "${ROOTSYS}/tutorials/eve/geom_lhcb.C"
```

The rendering is slow over X11 forwarding. I will try in the morning to run directly on my SL7 desktop to see if I can run without the extra env setting.

**Comment by gartung** [comment]
I checked this morning on my ScientificLinux 7 desktop and if I run without 
env LIBGL_ALWAYS_INDIRECT=1
The window manager either restarts or the window hangs. 
Because the X11 libraries included in the tarball are linked against the Centos6 version of libGL and libGLdispatch they can only be used directly if the host is also Centos6 or SLC6.

Does conda-forge offer a Centos7 docker image to build in?

**Comment by gartung** [comment]
@chrisburr Are you able to do a macOS build and put it on your channel?

**Comment by henryiii** [comment]
I can try to make a local build tomorrow on my mac.

**Comment by gartung** [comment]
I am trying a local build on my mac. I am trying to reproduce the steps manually from azure-pipelines-osx.yml

**Comment by chrisburr** [comment]
Thanks for testing. My mac is slowly dying and kernel panics whenever I try to build ROOT but if [you've set up the SDK](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html?highlight=SDK#macos-sdk) you should be able to replicate conda's build using:
```bash
conda build ./recipe -m ./.ci_support/osx_python3.7.yaml --clobber-file ./.ci_support/clobber_osx_python3.7.yaml
```

> Does conda-forge offer a Centos7 docker image to build in?

Building inside the CentOS 6 container shouldn't be an issue. The build links against Anaconda's OpenGL binaries that are repackaged from CentOS 6 ([known as CDTs](http://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cdt#core-dependency-tree-packages-cdt)) with the intention of being forwards compatible with newer Linux distributions.

I think the issue with ROOT is that RHEL7's build of OpenGL dynamically links to LLVM (see [here](https://sft.its.cern.ch/jira/browse/ROOT-9965), [here](https://cern.service-now.com/service-portal/view-incident.do?n=INC1242141) and [here](https://sft.its.cern.ch/jira/browse/ROOT-7744)). I haven't figured out how to avoid this problem and probably won't have time to devote it this week.

**Comment by gartung** [comment]
Yes I have the SDK installed.
 I am primarily interested in getting a macOS build so I can build the Fireworks application against that. 
Thanks for the command line.

**Comment by gartung** [comment]
My macOS build works with the test commands for OpenGL. Now on to testing the build of Fireworks!

**Comment by gartung** [comment]
More good news: after doing a fresh install of ScientificLinux 7.6 on my desktop I can run the GL test commands without 
env LIBGL_ALWAYS_INDIRECT=1

**Comment by gartung** [comment]
> More good news: after doing a fresh install of ScientificLinux 7.6 on my desktop I can run the GL test commands without
> env LIBGL_ALWAYS_INDIRECT=1

I should also note that I blacklisted the nouveau x11 driver so I could use the proprietary Nvidia driver.

**Comment by henryiii** [comment]
Will this / is this needed for the LLVM/Clang recipe?

**Comment by chrisburr** [comment]
> I should also note that I blacklisted the nouveau x11 driver so I could use the proprietary Nvidia driver.

That's reassuring, I was confused about how reinstalling could fix this problem.

> Will this / is this needed for the LLVM/Clang recipe?

No. If I understand this correctly, ROOT should be patched to use `--exclude-libs` (or something similar) instead of relying on the fact that LLVM and clang have been built with `-fvisibility=hidden`.

I checked using `nm` and the symbols are still global on macOS. It might cause a problem one day but I don't know a nice way of hiding them.

Assuming this PR passes the tests it should be fixed and ready to merge.

**Pull request merged**
